[package]
name = "advent_of_code_2018"
version = "0.1.0"
edition = "2024"
authors = ["William John Holden <wjholden@users.noreply.github.com>"]

[dependencies]
num-complex = "0.4.6"

[lints.rust]
unsafe_code = "forbid"
